#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
logout:
    path: /logout

pageNotFound:
    path:  /{path}
    defaults: { _controller: 'App\Controller\HomeController::errorAction', path: '' }
    requirements:
        path: .*